package com.gci.siarp.generales.ui;

import java.util.function.Consumer;

import com.gci.siarp.generales.domain.Afiliado;
import com.gci.siarp.generales.domain.Siniestro;
import com.gci.siarp.generales.domain.TipoDocumento;
import com.gci.siarp.generales.service.GeneralesService;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanContainer;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Notification.Type;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

public class BuscarSiniestroForm extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private Button bt_cancel;
	@AutoGenerated
	private Button bt_ok;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;
	@AutoGenerated
	private Table tb_siniestros;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private TextField tF_nombre;
	@AutoGenerated
	private Button bt_buscar;
	@AutoGenerated
	private TextField tF_docu;
	@AutoGenerated
	private ComboBox cB_tDoc;
	private Consumer<Siniestro> iConsumerUsarSiniestro;
	private Afiliado iAfiliado;
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BeanItemContainer<Siniestro> containerSinis;
	private GeneralesService iGeneralesService;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public BuscarSiniestroForm(Afiliado aAfiliado,GeneralesService aGeneralesServ,String asTipo,Boolean abnEsJuridico,Consumer<Siniestro> aUsarSiniestro) {
		iAfiliado=aAfiliado;
		iGeneralesService=aGeneralesServ;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		iConsumerUsarSiniestro=aUsarSiniestro;
		tF_docu.setEnabled(false);
		tF_nombre.setEnabled(false);
		
		containerSinis=new BeanItemContainer<Siniestro>(Siniestro.class);
		cB_tDoc.setVisible(false);
		bt_buscar.setVisible(false);
		
		tb_siniestros.setContainerDataSource(containerSinis);
		tb_siniestros.setSelectable(true);
		tb_siniestros.setImmediate(true);
		tb_siniestros.setVisibleColumns("idSiniestro","fechaAT","TDocEmpre","docEmpre","tipo","fechaMuerte","PCL");
		tb_siniestros.setColumnHeaders("Siniestro","fecha AT","tDoc Empre","Doc. Empresa","Tipo Siniestro","Fecha Muerte","PCL");
		
		if (aAfiliado==null){
			tF_docu.setEnabled(true);
			cB_tDoc.setVisible(true);
			bt_buscar.setVisible(true);
			
			BeanContainer<String, TipoDocumento> tiposdoc = new BeanContainer<String, TipoDocumento>(TipoDocumento.class);
			tiposdoc.setBeanIdProperty("tipoDoc");
			tiposdoc.addAll(aGeneralesServ.findAllTiposDocumento());
			cB_tDoc.setContainerDataSource(tiposdoc);
			cB_tDoc.setItemCaptionPropertyId("nombreDocu");
			cB_tDoc.setNullSelectionAllowed(false);
			cB_tDoc.setValue("CC");
			
		}else{
			tF_docu.setValue(aAfiliado.getIdPersona());
			String lsNombre;
			lsNombre=aAfiliado.getNombre1();
			if (aAfiliado.getNombre2()!=null) lsNombre+=" "+aAfiliado.getNombre2();
			lsNombre+=" "+aAfiliado.getApellido1();
			if (aAfiliado.getApellido2()!=null) lsNombre+=" "+aAfiliado.getApellido2();
			tF_nombre.setValue(lsNombre);
			if (!abnEsJuridico)
				containerSinis.addAll(aGeneralesServ.findSiniestros(aAfiliado.getIdTipoDoc(), aAfiliado.getIdPersona(),asTipo));
			else{
				String lsTipo="JI";
				if (asTipo.equals("PS")) lsTipo="JS";
				containerSinis.addAll(aGeneralesServ.findSiniestros(aAfiliado.getIdTipoDoc(), aAfiliado.getIdPersona(),lsTipo));
			}
				
		}
		
		tb_siniestros.setValue(null);

		bt_cancel.addClickListener(this::cancelar);
		bt_ok.addClickListener(this::aceptar);
		bt_buscar.addClickListener(this::clickBuscar);
		
	}
	
	
	private void cancelar(ClickEvent clickEvent){
		UI.getCurrent().removeWindow((Window) this.getParent());
	};
	
	private void aceptar(ClickEvent clickEvent){
		Siniestro siniestro=new Siniestro();
		
		siniestro=(Siniestro)tb_siniestros.getValue();
		if (siniestro==null){
			Notification.show("Debe seleccionar un siniestro de la lista para continuar",Type.WARNING_MESSAGE);
			return;
		}
		siniestro.setNombre1(iAfiliado.getNombre1());
		siniestro.setNombre2(iAfiliado.getNombre2());
		siniestro.setApellido1(iAfiliado.getApellido1());
		siniestro.setApellido2(iAfiliado.getApellido2());
		iConsumerUsarSiniestro.accept(siniestro);
		UI.getCurrent().removeWindow((Window) this.getParent());
	}
	
	private void clickBuscar(ClickEvent event){
		if (cB_tDoc.isEmpty()){
			Notification.show("Atención","Debe elegir el tipo de documento",Type.WARNING_MESSAGE);
			cB_tDoc.focus();
			return;
		}
		if (tF_docu.getValue().trim().equals("")){
			Notification.show("Atención","Debe digitar el documento",Type.WARNING_MESSAGE);
			tF_docu.focus();
			return;
		}
		iAfiliado=iGeneralesService.findAfiliado((String)cB_tDoc.getValue(), tF_docu.getValue().trim());
		containerSinis.removeAllItems();
		tb_siniestros.setValue(null);
		if (iAfiliado==null){
			Notification.show("Atención","No existe un afiliado con estos datos",Type.WARNING_MESSAGE);
			return;
		}
		String lsNombre;
		lsNombre=iAfiliado.getNombre1();
		if (iAfiliado.getNombre2()!=null) lsNombre+=" "+iAfiliado.getNombre2();
		lsNombre+=" "+iAfiliado.getApellido1();
		if (iAfiliado.getApellido2()!=null) lsNombre+=" "+iAfiliado.getApellido2();
		tF_nombre.setValue(lsNombre);
		
		containerSinis.addAll(iGeneralesService.findSiniestros(iAfiliado.getIdTipoDoc(), iAfiliado.getIdPersona(),""));
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("900px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("900px");
		setHeight("-1px");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		mainLayout.addComponent(horizontalLayout_3);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		mainLayout.addComponent(horizontalLayout_2);
		mainLayout.setComponentAlignment(horizontalLayout_2, new Alignment(24));
		
		return mainLayout;
	}


	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);
		
		// cB_tDoc
		cB_tDoc = new ComboBox();
		cB_tDoc.setCaption("Tipo Documento");
		cB_tDoc.setImmediate(false);
		cB_tDoc.setWidth("-1px");
		cB_tDoc.setHeight("-1px");
		horizontalLayout_1.addComponent(cB_tDoc);
		
		// tF_docu
		tF_docu = new TextField();
		tF_docu.setCaption("Documento");
		tF_docu.setImmediate(false);
		tF_docu.setWidth("-1px");
		tF_docu.setHeight("-1px");
		horizontalLayout_1.addComponent(tF_docu);
		
		// bt_buscar
		bt_buscar = new Button();
		bt_buscar.setCaption("Buscar");
		bt_buscar.setImmediate(false);
		bt_buscar.setWidth("-1px");
		bt_buscar.setHeight("-1px");
		horizontalLayout_1.addComponent(bt_buscar);
		horizontalLayout_1.setComponentAlignment(bt_buscar, new Alignment(9));
		
		// tF_nombre
		tF_nombre = new TextField();
		tF_nombre.setCaption("Afiliado");
		tF_nombre.setImmediate(false);
		tF_nombre.setWidth("400px");
		tF_nombre.setHeight("-1px");
		horizontalLayout_1.addComponent(tF_nombre);
		
		return horizontalLayout_1;
	}


	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setImmediate(false);
		horizontalLayout_3.setWidth("100.0%");
		horizontalLayout_3.setHeight("-1px");
		horizontalLayout_3.setMargin(false);
		
		// tb_siniestros
		tb_siniestros = new Table();
		tb_siniestros.setCaption("Siniestros del Afiliado");
		tb_siniestros.setImmediate(false);
		tb_siniestros.setWidth("100.0%");
		tb_siniestros.setHeight("250px");
		horizontalLayout_3.addComponent(tb_siniestros);
		
		return horizontalLayout_3;
	}


	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("-1px");
		horizontalLayout_2.setHeight("-1px");
		horizontalLayout_2.setMargin(false);
		horizontalLayout_2.setSpacing(true);
		
		// bt_ok
		bt_ok = new Button();
		bt_ok.setCaption("Aceptar");
		bt_ok.setImmediate(true);
		bt_ok.setWidth("-1px");
		bt_ok.setHeight("-1px");
		horizontalLayout_2.addComponent(bt_ok);
		
		// bt_cancel
		bt_cancel = new Button();
		bt_cancel.setCaption("Cancelar");
		bt_cancel.setImmediate(true);
		bt_cancel.setWidth("-1px");
		bt_cancel.setHeight("-1px");
		horizontalLayout_2.addComponent(bt_cancel);
		
		return horizontalLayout_2;
	}

}
