package com.gci.siarp.generales.ui;

import java.util.function.Consumer;

import com.gci.siarp.api.ui.SiarpTheme;
import com.gci.siarp.generales.domain.Afiliado;
import com.gci.siarp.generales.domain.TipoDocumento;
import com.gci.siarp.generales.service.GeneralesService;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanContainer;
import com.vaadin.server.FontAwesome;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Notification.Type;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

public class BuscarAfiliadoForm extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private Button bt_cancel;
	@AutoGenerated
	private Button bt_ok;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private TextField tF_nombre;
	@AutoGenerated
	private Button bt_buscar;
	@AutoGenerated
	private TextField tF_docu;
	@AutoGenerated
	private ComboBox cB_tDoc;
	private Consumer<Afiliado> iConsumerUsarAfiliado;
	private Afiliado iAfiliado=null;
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private GeneralesService iGeneralesService;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public BuscarAfiliadoForm(GeneralesService aGeneralesServ,Consumer<Afiliado> aUsarAfiliado) {

		iGeneralesService=aGeneralesServ;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		iConsumerUsarAfiliado=aUsarAfiliado;
		
			
		BeanContainer<String, TipoDocumento> tiposdoc = new BeanContainer<String, TipoDocumento>(TipoDocumento.class);
		tiposdoc.setBeanIdProperty("tipoDoc");
		tiposdoc.addAll(aGeneralesServ.findAllTiposDocumento());
		cB_tDoc.setContainerDataSource(tiposdoc);
		cB_tDoc.setItemCaptionPropertyId("nombreDocu");
		cB_tDoc.setNullSelectionAllowed(false);
		cB_tDoc.setValue("CC");

		bt_cancel.addClickListener(this::cancelar);
		bt_ok.addClickListener(this::aceptar);
		bt_buscar.addClickListener(this::clickBuscar);
		
		bt_buscar.setIcon(FontAwesome.SEARCH);
		
		bt_ok.addStyleName(SiarpTheme.BUTTON_FRIENDLY);
		bt_ok.setIcon(FontAwesome.PLUS_CIRCLE);
		bt_cancel.addStyleName(SiarpTheme.BUTTON_DANGER);
		bt_cancel.setIcon(FontAwesome.MINUS_CIRCLE);
	}
	
	
	private void cancelar(ClickEvent clickEvent){
		UI.getCurrent().removeWindow((Window) this.getParent());
	};
	
	private void aceptar(ClickEvent clickEvent){
		if (iAfiliado==null){
			Notification.show("Atención","Debe buscar un afiliado para continuar",Type.WARNING_MESSAGE);
			tF_docu.focus();
			return;
		}
		iConsumerUsarAfiliado.accept(iAfiliado);
		UI.getCurrent().removeWindow((Window) this.getParent());
	}
	
	private void clickBuscar(ClickEvent event){
		if (cB_tDoc.isEmpty()){
			Notification.show("Atención","Debe elegir el tipo de documento",Type.WARNING_MESSAGE);
			cB_tDoc.focus();
			return;
		}
		if (tF_docu.getValue().trim().equals("")){
			Notification.show("Atención","Debe digitar el documento",Type.WARNING_MESSAGE);
			tF_docu.focus();
			return;
		}
		iAfiliado=iGeneralesService.findAfiliado((String)cB_tDoc.getValue(), tF_docu.getValue().trim());
	
		if (iAfiliado==null){
			Notification.show("Atención","No existe un afiliado con estos datos",Type.WARNING_MESSAGE);
			return;
		}
		String lsNombre;
		lsNombre=iAfiliado.getNombre1();
		if (iAfiliado.getNombre2()!=null) lsNombre+=" "+iAfiliado.getNombre2();
		lsNombre+=" "+iAfiliado.getApellido1();
		if (iAfiliado.getApellido2()!=null) lsNombre+=" "+iAfiliado.getApellido2();
		tF_nombre.setValue(lsNombre);
	
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("840px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("840px");
		setHeight("-1px");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		mainLayout.addComponent(horizontalLayout_2);
		mainLayout.setComponentAlignment(horizontalLayout_2, new Alignment(24));
		
		return mainLayout;
	}


	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);
		
		// cB_tDoc
		cB_tDoc = new ComboBox();
		cB_tDoc.setCaption("Tipo Documento");
		cB_tDoc.setImmediate(false);
		cB_tDoc.setWidth("-1px");
		cB_tDoc.setHeight("-1px");
		horizontalLayout_1.addComponent(cB_tDoc);
		
		// tF_docu
		tF_docu = new TextField();
		tF_docu.setCaption("Documento");
		tF_docu.setImmediate(false);
		tF_docu.setWidth("-1px");
		tF_docu.setHeight("-1px");
		horizontalLayout_1.addComponent(tF_docu);
		
		// bt_buscar
		bt_buscar = new Button();
		bt_buscar.setCaption("Buscar");
		bt_buscar.setImmediate(true);
		bt_buscar.setWidth("-1px");
		bt_buscar.setHeight("-1px");
		horizontalLayout_1.addComponent(bt_buscar);
		horizontalLayout_1.setComponentAlignment(bt_buscar, new Alignment(9));
		
		// tF_nombre
		tF_nombre = new TextField();
		tF_nombre.setCaption("Afiliado");
		tF_nombre.setImmediate(false);
		tF_nombre.setWidth("400px");
		tF_nombre.setHeight("-1px");
		horizontalLayout_1.addComponent(tF_nombre);
		
		return horizontalLayout_1;
	}


	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("-1px");
		horizontalLayout_2.setHeight("-1px");
		horizontalLayout_2.setMargin(false);
		horizontalLayout_2.setSpacing(true);
		
		// bt_ok
		bt_ok = new Button();
		bt_ok.setCaption("Aceptar");
		bt_ok.setImmediate(true);
		bt_ok.setWidth("-1px");
		bt_ok.setHeight("-1px");
		horizontalLayout_2.addComponent(bt_ok);
		
		// bt_cancel
		bt_cancel = new Button();
		bt_cancel.setCaption("Cancelar");
		bt_cancel.setImmediate(true);
		bt_cancel.setWidth("-1px");
		bt_cancel.setHeight("-1px");
		horizontalLayout_2.addComponent(bt_cancel);
		
		return horizontalLayout_2;
	}

}
