package com.gci.siarp.generales.ui;

import com.gci.siarp.api.ui.SiarpTheme;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.FontAwesome;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

@SuppressWarnings("serial")
public class Messagebox extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private HorizontalLayout hL_YesNoCancel;
	@AutoGenerated
	private Button bt_cancel;
	@AutoGenerated
	private Button bt_no;
	@AutoGenerated
	private Button bt_yes;
	@AutoGenerated
	private TextArea tA_message;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Messagebox(String as_message,String as_botones,ClickListener eventSi) {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		bt_yes.addStyleName(SiarpTheme.BUTTON_FRIENDLY);
		bt_yes.setIcon(FontAwesome.CHECK);
		bt_cancel.addStyleName(SiarpTheme.BUTTON_DANGER);
		bt_cancel.setIcon(FontAwesome.MINUS_CIRCLE);
		bt_no.addStyleName(SiarpTheme.BUTTON_DANGER);
		bt_no.setIcon(FontAwesome.MINUS_CIRCLE);
		tA_message.setValue(as_message);
		tA_message.setReadOnly(true);
		if (eventSi!=null) bt_yes.addClickListener(eventSi);
		if (as_botones=="yesno"){
			bt_no.addClickListener(e ->{UI.getCurrent().removeWindow((Window) this.getParent());});
			bt_cancel.setVisible(false);
		}
		if (as_botones=="aceptar"){
			bt_yes.setCaption("Aceptar");
			bt_no.setVisible(false);
			bt_cancel.setVisible(false);
		}
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("379px");
		mainLayout.setHeight("200px");
		
		// top-level component properties
		setWidth("379px");
		setHeight("200px");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		mainLayout.addComponent(verticalLayout_1, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("-1px");
		verticalLayout_1.setHeight("-1px");
		verticalLayout_1.setMargin(true);
		verticalLayout_1.setSpacing(true);
		
		// tA_message
		tA_message = new TextArea();
		tA_message.setImmediate(false);
		tA_message.setWidth("340px");
		tA_message.setHeight("-1px");
		verticalLayout_1.addComponent(tA_message);
		
		// hL_YesNoCancel
		hL_YesNoCancel = buildHL_YesNoCancel();
		verticalLayout_1.addComponent(hL_YesNoCancel);
		verticalLayout_1.setComponentAlignment(hL_YesNoCancel, new Alignment(48));
		
		return verticalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHL_YesNoCancel() {
		// common part: create layout
		hL_YesNoCancel = new HorizontalLayout();
		hL_YesNoCancel.setImmediate(false);
		hL_YesNoCancel.setWidth("-1px");
		hL_YesNoCancel.setHeight("-1px");
		hL_YesNoCancel.setMargin(false);
		hL_YesNoCancel.setSpacing(true);
		
		// bt_yes
		bt_yes = new Button();
		bt_yes.setCaption("Si");
		bt_yes.setImmediate(true);
		bt_yes.setWidth("-1px");
		bt_yes.setHeight("-1px");
		hL_YesNoCancel.addComponent(bt_yes);
		
		// bt_no
		bt_no = new Button();
		bt_no.setCaption("No");
		bt_no.setImmediate(true);
		bt_no.setWidth("-1px");
		bt_no.setHeight("-1px");
		hL_YesNoCancel.addComponent(bt_no);
		
		// bt_cancel
		bt_cancel = new Button();
		bt_cancel.setCaption("Cancelar");
		bt_cancel.setImmediate(true);
		bt_cancel.setWidth("-1px");
		bt_cancel.setHeight("-1px");
		hL_YesNoCancel.addComponent(bt_cancel);
		
		return hL_YesNoCancel;
	}

}
