package com.gci.siarp.generales.ui;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;

import com.gci.siarp.api.ui.SiarpTheme;
import com.gci.siarp.generales.domain.IBC;
import com.gci.siarp.generales.service.IBCService;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.FontAwesome;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.ValoTheme;

public class ObjMuestraIbcs extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button bt_delete;
	@AutoGenerated
	private Button bt_insert;
	@AutoGenerated
	private Panel panel_1;
	@AutoGenerated
	private VerticalLayout vL_filas;
	@AutoGenerated
	private GridLayout gridLayout_1;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private Label label_4;
	@AutoGenerated
	private Label label_5;
	@AutoGenerated
	private Button bT_sel;
	private Collection<IBC> iIbcs;
	private ArrayList<ObjEditIBC> iFilasIbcs;
	private boolean iBlSelecc=true;
	private ObjEditIBC iIBCActual;
	private IBCService iIBCService;
	private Integer iiIdSolicitud;
	private String isOrigen; //IP: IPP, PE:Pensiones
	private Date idFechaSini;
	private String isTipoSini;
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ObjMuestraIbcs(IBCService aIBCServ) {
		iIBCService=aIBCServ;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		iniciar();
	}
	
	private void cambioFila(ObjEditIBC aIBC){
		iIBCActual=aIBC;
	}
	
	public void update(){
		for (Integer j=0;j<iFilasIbcs.size();j++){
			iFilasIbcs.get(j).update(isOrigen);
		}
	}
	
	public Boolean isValid(){
		if (iFilasIbcs==null) return false;
		if (iFilasIbcs.size()==0) return false;
		for (Integer j=0;j<iFilasIbcs.size();j++){
			if (!iFilasIbcs.get(j).isValid()) return false;
		}
		return true;
	}
	
	public Boolean isValidCero(){
		if (iFilasIbcs==null) return true;
		if (iFilasIbcs.size()==0) return true;
		for (Integer j=0;j<iFilasIbcs.size();j++){
			if (!iFilasIbcs.get(j).isValid()) return false;
		}
		return true;
	}
	
	private void iniciar(){
		label_1.setStyleName(SiarpTheme.TEXTFIELD_ALIGN_CENTER);
		label_2.setStyleName(SiarpTheme.TEXTFIELD_ALIGN_CENTER);
		label_3.setStyleName(SiarpTheme.TEXTFIELD_ALIGN_CENTER);
		label_4.setStyleName(SiarpTheme.TEXTFIELD_ALIGN_CENTER);
		label_5.setStyleName(SiarpTheme.TEXTFIELD_ALIGN_CENTER);
		bT_sel.setStyleName("link");
		bT_sel.addClickListener(this::seleccionar);
		bT_sel.setCaption("");
		bT_sel.setIcon(FontAwesome.CHECK);
		bT_sel.addStyleName(SiarpTheme.BUTTON_ICON_ONLY);
		panel_1.setStyleName(ValoTheme.PANEL_BORDERLESS);

		bt_insert.addClickListener(this::clickInsertar);
		bt_delete.addClickListener(this::clickDelete);
		iFilasIbcs=new ArrayList<ObjEditIBC>();
	}
	private void seleccionar(ClickEvent event){
		iBlSelecc=!iBlSelecc;
		for (int i=0;i<iFilasIbcs.size() ;i++){
			iFilasIbcs.get(i).getCheck().setValue(iBlSelecc);
		}
	}
	
	public void show(Integer aiIdSolicitud,Collection<IBC> aIbcs,String asOrigen,Date adFechaSini,String asTipoSini){
		isTipoSini=asTipoSini;
		idFechaSini=adFechaSini;
		isOrigen=asOrigen;
		iiIdSolicitud=aiIdSolicitud;
		iIbcs=aIbcs;
		vL_filas.removeAllComponents();
		ObjEditIBC loIBC;
		for(IBC ibc : iIbcs) {
			loIBC=new ObjEditIBC(ibc,false,this::cambioFila,iIBCService,idFechaSini,asTipoSini);
			iFilasIbcs.add(loIBC);
			vL_filas.addComponent(loIBC);
		}
	}
	
	public Collection<IBC> getIBCs(){
		List<IBC> myList = new ArrayList<IBC>();
		for (int i=0;i<iFilasIbcs.size();i++){
			myList.add(iFilasIbcs.get(i).getIBC());
		}
		return myList;
	}
	
	private void clickInsertar(ClickEvent event){
		IBC lIBC=new IBC();
		lIBC.setIdSolicitud(iiIdSolicitud);
		lIBC.setSeleccionado("1");
		ObjEditIBC loIBC=new ObjEditIBC(lIBC,true,this::cambioFila,iIBCService,idFechaSini,isTipoSini);
		iFilasIbcs.add(loIBC);
		vL_filas.addComponent(loIBC);
		loIBC.focus();
	}
	
	
	private void clickDelete(ClickEvent event){
		if (iIBCActual!=null){
			if (iIBCActual.getItemStatus().equals("New") || iIBCActual.getItemStatus().equals("NewModified")){
				vL_filas.removeComponent(iIBCActual);
				iFilasIbcs.remove(iIBCActual);
				iIBCActual=null;
			}
		}
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("500px");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("500px");
		setHeight("100.0%");
		
		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		mainLayout.addComponent(gridLayout_1, "top:24.0px;left:0.0px;");
		
		// panel_1
		panel_1 = buildPanel_1();
		mainLayout.addComponent(panel_1, "top:44.0px;left:0.0px;");
		
		// bt_insert
		bt_insert = new Button();
		bt_insert.setCaption("Insertar");
		bt_insert.setImmediate(true);
		bt_insert.setWidth("-1px");
		bt_insert.setHeight("24px");
		mainLayout.addComponent(bt_insert, "top:1.0px;left:1.0px;");
		
		// bt_delete
		bt_delete = new Button();
		bt_delete.setCaption("Eliminar");
		bt_delete.setImmediate(true);
		bt_delete.setWidth("-1px");
		bt_delete.setHeight("24px");
		mainLayout.addComponent(bt_delete, "top:1.0px;left:73.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("-1px");
		gridLayout_1.setHeight("-1px");
		gridLayout_1.setMargin(false);
		gridLayout_1.setColumns(6);
		
		// bT_sel
		bT_sel = new Button();
		bT_sel.setCaption("Sel.");
		bT_sel.setImmediate(true);
		bT_sel.setWidth("16px");
		bT_sel.setHeight("20px");
		gridLayout_1.addComponent(bT_sel, 0, 0);
		
		// label_5
		label_5 = new Label();
		label_5.setImmediate(false);
		label_5.setWidth("101px");
		label_5.setHeight("-1px");
		label_5.setValue("IBC");
		gridLayout_1.addComponent(label_5, 1, 0);
		
		// label_4
		label_4 = new Label();
		label_4.setImmediate(false);
		label_4.setWidth("125px");
		label_4.setHeight("-1px");
		label_4.setValue("Fecha (yyyy-mm)");
		gridLayout_1.addComponent(label_4, 2, 0);
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("70px");
		label_3.setHeight("-1px");
		label_3.setValue("Días");
		gridLayout_1.addComponent(label_3, 3, 0);
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("103px");
		label_2.setHeight("-1px");
		label_2.setValue("Nuevo IBC");
		gridLayout_1.addComponent(label_2, 4, 0);
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("70px");
		label_1.setHeight("-1px");
		label_1.setValue("Nue.Días");
		gridLayout_1.addComponent(label_1, 5, 0);
		
		return gridLayout_1;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setImmediate(false);
		panel_1.setWidth("100.0%");
		panel_1.setHeight("100.0%");
		
		// vL_filas
		vL_filas = new VerticalLayout();
		vL_filas.setImmediate(false);
		vL_filas.setWidth("100.0%");
		vL_filas.setHeight("-1px");
		vL_filas.setMargin(false);
		panel_1.setContent(vL_filas);
		
		return panel_1;
	}

}
