package com.gci.siarp.generales.ui;

import java.util.function.Consumer;

import com.gci.siarp.api.ui.SiarpTheme;
import com.gci.siarp.generales.domain.Afiliado;
import com.gci.siarp.generales.domain.TipoDocumento;
import com.gci.siarp.generales.service.GeneralesService;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.data.fieldgroup.FieldGroup.CommitException;
import com.vaadin.data.util.BeanContainer;
import com.vaadin.data.util.BeanItem;
import com.vaadin.server.FontAwesome;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Notification.Type;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

public class PersonaNoAfiliadaForm extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private Button bt_cancel;
	@AutoGenerated
	private Button bt_ok;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_4;
	@AutoGenerated
	private TextField tF_apellido2;
	@AutoGenerated
	private TextField tF_apellido1;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;
	@AutoGenerated
	private TextField tF_nombre2;
	@AutoGenerated
	private TextField tF_nombre1;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private TextField tF_docu;
	@AutoGenerated
	private ComboBox cB_tDoc;
	private Consumer<Afiliado> iConsumerUsarAfiliado;
	private Afiliado iAfiliado=null;
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private GeneralesService iGeneralesService;
	
	private FieldGroup iFGPersona;
	private BeanItem<Afiliado> iBIPersona;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public PersonaNoAfiliadaForm(GeneralesService aGeneralesServ,Consumer<Afiliado> aUsarAfiliado) {

		iGeneralesService=aGeneralesServ;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		iConsumerUsarAfiliado=aUsarAfiliado;
		
			
		BeanContainer<String, TipoDocumento> tiposdoc = new BeanContainer<String, TipoDocumento>(TipoDocumento.class);
		tiposdoc.setBeanIdProperty("tipoDoc");
		tiposdoc.addAll(aGeneralesServ.findAllTiposDocumento());
		cB_tDoc.setContainerDataSource(tiposdoc);
		cB_tDoc.setItemCaptionPropertyId("nombreDocu");
		cB_tDoc.setNullSelectionAllowed(false);
		cB_tDoc.addValueChangeListener(this::cambiaTdoc);
		cB_tDoc.setImmediate(true);
		
		tF_docu.setImmediate(true);
		tF_docu.addValueChangeListener(this::cambiaDocu);

		bt_cancel.addClickListener(this::cancelar);
		bt_ok.addClickListener(this::aceptar);
	
		
		bt_ok.addStyleName(SiarpTheme.BUTTON_FRIENDLY);
		bt_ok.setIcon(FontAwesome.PLUS_CIRCLE);
		bt_cancel.addStyleName(SiarpTheme.BUTTON_DANGER);
		bt_cancel.setIcon(FontAwesome.MINUS_CIRCLE);
		
		
		ponerFormatos();
		binder();
		habilitarValidaciones(false);
	}
	
	private void binder(){

		iFGPersona=new FieldGroup(iBIPersona);
		
		iFGPersona.bind(tF_docu, "idPersona");
		iFGPersona.bind(cB_tDoc, "idTipoDoc");
		
		iFGPersona.bind(tF_nombre1, "nombre1");
		iFGPersona.bind(tF_nombre2, "nombre2");
		iFGPersona.bind(tF_apellido1, "apellido1");
		iFGPersona.bind(tF_apellido2, "apellido2");
		cB_tDoc.setValue("CC");
	}
	
	
	private void cancelar(ClickEvent clickEvent){
		UI.getCurrent().removeWindow((Window) this.getParent());
	};
	
	private void aceptar(ClickEvent clickEvent){
		try{
			iFGPersona.commit();
		}catch (CommitException ex) {
			Notification.show("Aviso!", "Verifique la información del formulario.", Type.WARNING_MESSAGE);
			habilitarValidaciones(true);
			return ;
		}
	
		iConsumerUsarAfiliado.accept(iAfiliado);
		UI.getCurrent().removeWindow((Window) this.getParent());
	}
	
	private void cambiaDocu(ValueChangeEvent event){
		
		String lsTdoc=(String)cB_tDoc.getValue();
		String lsDoc=null;
		Boolean lbnHabilitar=false;
		
		if (tF_docu.getValue()!=null) lsDoc=tF_docu.getValue().trim();
		
		iAfiliado=iGeneralesService.findAfiliado(lsTdoc, lsDoc);
		
		if (iAfiliado==null){
			lbnHabilitar=true;
			iAfiliado=new Afiliado();
			iAfiliado.setIdTipoDoc(lsTdoc);
			iAfiliado.setIdPersona(lsDoc);
		}
		
		iBIPersona=new BeanItem<Afiliado>(iAfiliado);
		iFGPersona.setItemDataSource(iBIPersona);
		
		habilitarCampos(lbnHabilitar);
	
	}
	
	private void cambiaTdoc(ValueChangeEvent event){
		tF_docu.setValue("");
		tF_nombre1.setValue("");
		tF_nombre2.setValue("");
		tF_apellido1.setValue("");
		tF_apellido2.setValue("");
		habilitarCampos(true);
	}
	
	private void ponerFormatos(){
		cB_tDoc.setRequired(true);
		cB_tDoc.setRequiredError("El Tipo de Documento es requerido");
		
		tF_docu.setNullRepresentation("");
		tF_docu.setRequired(true);
		tF_docu.setRequiredError("El Documento es requerido");
		
		
		tF_nombre1.setNullRepresentation("");
		tF_nombre1.setRequired(true);
		tF_nombre1.setRequiredError("El primer nombre es requerido");
		
		tF_nombre2.setNullRepresentation("");
		
		tF_apellido1.setNullRepresentation("");
		tF_apellido1.setRequired(true);
		tF_apellido1.setRequiredError("El primer apellido es requerido");
		
		tF_apellido2.setNullRepresentation("");
	}
	
	private void habilitarCampos(Boolean abnActivar){
		tF_nombre1.setEnabled(abnActivar);
		tF_nombre2.setEnabled(abnActivar);
		tF_apellido1.setEnabled(abnActivar);
		tF_apellido2.setEnabled(abnActivar);
	}
	
	private void habilitarValidaciones(Boolean abnHabilitar){
		cB_tDoc.setValidationVisible(abnHabilitar);
		tF_docu.setValidationVisible(abnHabilitar);
		tF_nombre1.setValidationVisible(abnHabilitar);
		tF_nombre2.setValidationVisible(abnHabilitar);
		tF_apellido1.setValidationVisible(abnHabilitar);
		tF_apellido2.setValidationVisible(abnHabilitar);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("440px");
		mainLayout.setHeight("240px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("440px");
		setHeight("240px");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		mainLayout.addComponent(horizontalLayout_3);
		
		// horizontalLayout_4
		horizontalLayout_4 = buildHorizontalLayout_4();
		mainLayout.addComponent(horizontalLayout_4);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		mainLayout.addComponent(horizontalLayout_2);
		mainLayout.setComponentAlignment(horizontalLayout_2, new Alignment(24));
		
		return mainLayout;
	}


	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);
		
		// cB_tDoc
		cB_tDoc = new ComboBox();
		cB_tDoc.setCaption("Tipo Documento");
		cB_tDoc.setImmediate(false);
		cB_tDoc.setWidth("100.0%");
		cB_tDoc.setHeight("-1px");
		horizontalLayout_1.addComponent(cB_tDoc);
		
		// tF_docu
		tF_docu = new TextField();
		tF_docu.setCaption("Documento");
		tF_docu.setImmediate(false);
		tF_docu.setWidth("100.0%");
		tF_docu.setHeight("-1px");
		horizontalLayout_1.addComponent(tF_docu);
		
		return horizontalLayout_1;
	}


	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setImmediate(false);
		horizontalLayout_3.setWidth("100.0%");
		horizontalLayout_3.setHeight("-1px");
		horizontalLayout_3.setMargin(false);
		horizontalLayout_3.setSpacing(true);
		
		// tF_nombre1
		tF_nombre1 = new TextField();
		tF_nombre1.setCaption("Primer Nombre");
		tF_nombre1.setImmediate(false);
		tF_nombre1.setWidth("100.0%");
		tF_nombre1.setHeight("-1px");
		horizontalLayout_3.addComponent(tF_nombre1);
		
		// tF_nombre2
		tF_nombre2 = new TextField();
		tF_nombre2.setCaption("Segundo Nombre");
		tF_nombre2.setImmediate(false);
		tF_nombre2.setWidth("100.0%");
		tF_nombre2.setHeight("-1px");
		horizontalLayout_3.addComponent(tF_nombre2);
		
		return horizontalLayout_3;
	}


	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_4() {
		// common part: create layout
		horizontalLayout_4 = new HorizontalLayout();
		horizontalLayout_4.setImmediate(false);
		horizontalLayout_4.setWidth("100.0%");
		horizontalLayout_4.setHeight("-1px");
		horizontalLayout_4.setMargin(false);
		horizontalLayout_4.setSpacing(true);
		
		// tF_apellido1
		tF_apellido1 = new TextField();
		tF_apellido1.setCaption("Primer Apellido");
		tF_apellido1.setImmediate(false);
		tF_apellido1.setWidth("100.0%");
		tF_apellido1.setHeight("-1px");
		horizontalLayout_4.addComponent(tF_apellido1);
		
		// tF_apellido2
		tF_apellido2 = new TextField();
		tF_apellido2.setCaption("Segundo Apellido");
		tF_apellido2.setImmediate(false);
		tF_apellido2.setWidth("100.0%");
		tF_apellido2.setHeight("-1px");
		horizontalLayout_4.addComponent(tF_apellido2);
		
		return horizontalLayout_4;
	}


	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("-1px");
		horizontalLayout_2.setHeight("-1px");
		horizontalLayout_2.setMargin(false);
		horizontalLayout_2.setSpacing(true);
		
		// bt_ok
		bt_ok = new Button();
		bt_ok.setCaption("Aceptar");
		bt_ok.setImmediate(true);
		bt_ok.setWidth("-1px");
		bt_ok.setHeight("-1px");
		horizontalLayout_2.addComponent(bt_ok);
		
		// bt_cancel
		bt_cancel = new Button();
		bt_cancel.setCaption("Cancelar");
		bt_cancel.setImmediate(true);
		bt_cancel.setWidth("-1px");
		bt_cancel.setHeight("-1px");
		horizontalLayout_2.addComponent(bt_cancel);
		
		return horizontalLayout_2;
	}

}
